name: Pandoc build

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          path: main

      - name: Create output directory
        run: mkdir -p out

      - name: Make files accessible to pandoc
        id: files_list
        run: |
          echo "files=$(printf '"%s" ' main/*.md)" >> $GITHUB_OUTPUT

      - name: Current date
        id: date
        run: echo "date=$(date +"%Y-%m-%d %H:%M")" >> $GITHUB_OUTPUT

      - name: Install Fonts
        run: |
          sudo apt -y install fonts-noto fonts-roboto

          # Create font directory and mount point
          mkdir -p /tmp/fonts
          mkdir -p ~/.fonts
          
          # Update font cache
          fc-cache -fv ~/.fonts
          fc-cache -fv /tmp/fonts

      - uses: docker://pandoc/latex
        with:
          args: >-  # allows you to break string into multiple lines
            -i ${{ steps.files_list.outputs.files }}
            -f gfm
            --pdf-engine=xelatex
            -V mainfont="Roboto"
            -V monofont="Fira Code"
            -V geometry:a4paper
            -V geometry:margin=2cm
            --toc=true
            --metadata title="Abstrakte Maschinen Ausarbeitung - 2025S"
            --metadata date="${{ steps.date.outputs.date }}"
            -s
            -o out/script.pdf 
        env:
          HOME: /tmp

      - uses: docker://pandoc/latex
        with:
          args: >-  # allows you to break string into multiple lines
            -i ${{ steps.files_list.outputs.files }}
            -f gfm
            --pdf-engine=xelatex
            -V mainfont="Roboto"
            -V monofont="Fira Code"
            -V geometry:a4paper
            -V geometry:margin=2cm
            --toc=true
            --metadata title="Abstrakte Maschinen Ausarbeitung - 2025S"
            --metadata date="${{ steps.date.outputs.date }}"
            -s
            -o out/script.html
        env:
          HOME: /tmp

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: documents
          path: out/
