name: Pandoc build

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache APT packages
        uses: actions/cache@v4
        with:
          path: /var/cache/apt/archives
          key: ${{ runner.os }}-apt-cache

      - name: Update APT
        run: sudo apt update

      - name: Create output directory
        run: mkdir -p out

      - name: Install Fonts
        run: |
          sudo apt install -y fonts-firacode fonts-roboto pandoc texlive-xetex

      - name: Convert Markdown to PDF
        run: |
          pandoc \
              -i *.md \
              -f gfm \
              --pdf-engine=xelatex \
              -V mainfont="Roboto" \
              -V monofont="Fira Code" \
              -V geometry:a4paper \
              -V geometry:margin=2cm \
              --toc \
              --metadata title="Abstrakte Maschinen Ausarbeitung - 2025S" \
              --metadata date="$(date +"%Y-%m-%d %H:%M")" \
              --embed-resources --standalone \
              -o out/script.pdf 

          # HTMl
          pandoc \
              -i *.md \
              -f gfm \
              --pdf-engine=xelatex \
              -V mainfont="Roboto" \
              -V monofont="Fira Code" \
              -V geometry:a4paper \
              -V geometry:margin=2cm \
              --toc \
              --metadata title="Abstrakte Maschinen Ausarbeitung - 2025S" \
              --metadata date="$(date +"%Y-%m-%d %H:%M")" \
              --embed-resources --standalone \
              -o out/script.html

      - name: Delete existing release (if it exists)
        run: |
          gh release delete latest -y --cleanup-tag || true
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Create release
        run: |
          gh release create latest out/script.pdf out/script.html
        env:
          GH_TOKEN: ${{ github.token }}
