name: Build Documents

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup pandoc
        uses: setup-pandoc/action@v2
        id: pandoc
        with:
          texlive_version: '202103'
      
      - name: Install fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            fonts-roboto \
            fonts-firacode
            
      - name: Create output directory
        run: mkdir -p out
        
      - name: Run pandoc script
        run: |
          #!/usr/bin/env bash
          
          # A simple "build" script to combine all markdown files into a single pdf and html file
          # PDF: Requires pdflatex
          pandoc -i *.md \
              -f gfm \
              --pdf-engine=xelatex \
              -V mainfont="Roboto" \
              -V monofont="Fira Code" \
              -V geometry:a4paper \
              -V geometry:margin=2cm \
              --toc=true \
              --metadata title="Abstrakte Maschinen Ausarbeitung - 2025S" \
              --metadata date="$(date +"%Y-%m-%d %H:%M")" \
              -s \
              -o out/script.pdf 

          # HTMl
          pandoc -i *.md \
              -f gfm \
              --pdf-engine=xelatex \
              -V mainfont="Roboto" \
              -V monofont="Fira Code" \
              -V geometry:a4paper \
              -V geometry:margin=2cm \
              --toc=true \
              --metadata title="Abstrakte Maschinen Ausarbeitung - 2025S" \
              --metadata date="$(date +"%Y-%m-%d %H:%M")" \
              -s \
              -o out/script.html
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: documents
          path: out/
