name: Pandoc build

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          path: main

      - name: Create output directory
        run: mkdir -p out

      - name: Make files accessible to pandoc
        id: files_list
        run: |
          echo "files=$(printf '"%s" ' main/*.md)" >> $GITHUB_OUTPUT

      - name: Current date
        id: date
        run: echo "date=$(date +"%Y-%m-%d %H:%M")" >> $GITHUB_OUTPUT

      - name: Install Fonts
        run: |
          sudo apt install -y fonts-noto fonts-roboto
          sudo apt install -y pandoc texlive-xetex fonts-noto

      - name: Convert Markdown to PDF
        run: |
          pandoc \
              -i main/*.md \
              -f gfm \
              --pdf-engine=xelatex \
              -V mainfont="Roboto" \
              -V monofont="Fira Code" \
              -V geometry:a4paper \
              -V geometry:margin=2cm \
              --toc \
              --metadata title="Abstrakte Maschinen Ausarbeitung - 2025S" \
              --metadata date="$(date +"%Y-%m-%d %H:%M")" \
              -s \
              -o out/script.pdf 

          # HTMl
          pandoc \
              -i main/*.md \
              -f gfm \
              --pdf-engine=xelatex \
              -V mainfont="Roboto" \
              -V monofont="Fira Code" \
              -V geometry:a4paper \
              -V geometry:margin=2cm \
              --toc \
              --metadata title="Abstrakte Maschinen Ausarbeitung - 2025S" \
              --metadata date="$(date +"%Y-%m-%d %H:%M")" \
              -s \
              -o out/script.html

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: documents
          path: out/
